namespace ELEVATE_SHOP_MANAGER
{
    partial class home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(home));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.name = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuButton27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btthongke = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btquanlinhanvien = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnhapdon = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btkhohang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btqldonhang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btbanhang = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bthome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.Conten = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.bunifuGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BackColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuGroupBox1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuGroupBox1.BorderRadius = 0;
            this.bunifuGroupBox1.BorderThickness = 1;
            this.bunifuGroupBox1.Controls.Add(this.name);
            this.bunifuGroupBox1.Controls.Add(this.label1);
            this.bunifuGroupBox1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(1, -1);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(1911, 66);
            this.bunifuGroupBox1.TabIndex = 0;
            this.bunifuGroupBox1.TabStop = false;
            // 
            // name
            // 
            this.name.AutoSize = true;
            this.name.Font = new System.Drawing.Font("Segoe UI Semibold", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.name.ForeColor = System.Drawing.Color.DimGray;
            this.name.Location = new System.Drawing.Point(1539, 24);
            this.name.Name = "name";
            this.name.Size = new System.Drawing.Size(76, 31);
            this.name.TabIndex = 10;
            this.name.Text = "Name";
            this.name.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.name.Click += new System.EventHandler(this.name_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Segoe UI", 24F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.DimGray;
            this.label1.Location = new System.Drawing.Point(79, 6);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(311, 54);
            this.label1.TabIndex = 8;
            this.label1.Text = "ELEVATE STORE";
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = global::ELEVATE_SHOP_MANAGER.Properties.Resources.logo;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(19, 10);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(50, 50);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.bunifuPictureBox1.TabIndex = 7;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BackColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.Gray;
            this.bunifuGroupBox2.BorderRadius = 1;
            this.bunifuGroupBox2.BorderThickness = 2;
            this.bunifuGroupBox2.Controls.Add(this.label2);
            this.bunifuGroupBox2.Controls.Add(this.bunifuButton27);
            this.bunifuGroupBox2.Controls.Add(this.btthongke);
            this.bunifuGroupBox2.Controls.Add(this.btquanlinhanvien);
            this.bunifuGroupBox2.Controls.Add(this.btnhapdon);
            this.bunifuGroupBox2.Controls.Add(this.btkhohang);
            this.bunifuGroupBox2.Controls.Add(this.btqldonhang);
            this.bunifuGroupBox2.Controls.Add(this.btbanhang);
            this.bunifuGroupBox2.Controls.Add(this.bthome);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuGroupBox2.ForeColor = System.Drawing.Color.White;
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(1, 71);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(277, 924);
            this.bunifuGroupBox2.TabIndex = 1;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Enter += new System.EventHandler(this.bunifuGroupBox2_Enter);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Black", 10.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.DimGray;
            this.label2.Location = new System.Drawing.Point(6, 799);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(255, 23);
            this.label2.TabIndex = 9;
            this.label2.Text = "___________________________________";
            // 
            // bunifuButton27
            // 
            this.bunifuButton27.AllowAnimations = true;
            this.bunifuButton27.AllowMouseEffects = true;
            this.bunifuButton27.AllowToggling = false;
            this.bunifuButton27.AnimationSpeed = 200;
            this.bunifuButton27.AutoGenerateColors = false;
            this.bunifuButton27.AutoRoundBorders = false;
            this.bunifuButton27.AutoSizeLeftIcon = true;
            this.bunifuButton27.AutoSizeRightIcon = true;
            this.bunifuButton27.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton27.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton27.BackgroundImage")));
            this.bunifuButton27.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.ButtonText = "     Thoát";
            this.bunifuButton27.ButtonTextMarginLeft = 0;
            this.bunifuButton27.ColorContrastOnClick = 0;
            this.bunifuButton27.ColorContrastOnHover = 0;
            this.bunifuButton27.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton27.CustomizableEdges = borderEdges1;
            this.bunifuButton27.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton27.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton27.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton27.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton27.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton27.Font = new System.Drawing.Font("Segoe UI", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton27.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuButton27.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton27.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton27.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton27.IconMarginLeft = 11;
            this.bunifuButton27.IconPadding = 10;
            this.bunifuButton27.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton27.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton27.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton27.IconSize = 25;
            this.bunifuButton27.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.IdleBorderRadius = 30;
            this.bunifuButton27.IdleBorderThickness = 1;
            this.bunifuButton27.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.x;
            this.bunifuButton27.IdleIconRightImage = null;
            this.bunifuButton27.IndicateFocus = false;
            this.bunifuButton27.Location = new System.Drawing.Point(40, 838);
            this.bunifuButton27.Name = "bunifuButton27";
            this.bunifuButton27.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton27.OnDisabledState.BorderRadius = 30;
            this.bunifuButton27.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnDisabledState.BorderThickness = 1;
            this.bunifuButton27.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton27.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton27.OnDisabledState.IconLeftImage = null;
            this.bunifuButton27.OnDisabledState.IconRightImage = null;
            this.bunifuButton27.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.bunifuButton27.onHoverState.BorderRadius = 30;
            this.bunifuButton27.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.onHoverState.BorderThickness = 1;
            this.bunifuButton27.onHoverState.FillColor = System.Drawing.Color.Brown;
            this.bunifuButton27.onHoverState.ForeColor = System.Drawing.Color.LightGray;
            this.bunifuButton27.onHoverState.IconLeftImage = null;
            this.bunifuButton27.onHoverState.IconRightImage = null;
            this.bunifuButton27.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnIdleState.BorderRadius = 30;
            this.bunifuButton27.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnIdleState.BorderThickness = 1;
            this.bunifuButton27.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnIdleState.ForeColor = System.Drawing.Color.DarkGray;
            this.bunifuButton27.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.x;
            this.bunifuButton27.OnIdleState.IconRightImage = null;
            this.bunifuButton27.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnPressedState.BorderRadius = 30;
            this.bunifuButton27.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton27.OnPressedState.BorderThickness = 1;
            this.bunifuButton27.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.bunifuButton27.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuButton27.OnPressedState.IconLeftImage = null;
            this.bunifuButton27.OnPressedState.IconRightImage = null;
            this.bunifuButton27.Size = new System.Drawing.Size(192, 51);
            this.bunifuButton27.TabIndex = 8;
            this.bunifuButton27.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton27.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton27.TextMarginLeft = 0;
            this.bunifuButton27.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton27.UseDefaultRadiusAndThickness = true;
            this.bunifuButton27.Click += new System.EventHandler(this.bunifuButton27_Click);
            // 
            // btthongke
            // 
            this.btthongke.AllowAnimations = true;
            this.btthongke.AllowMouseEffects = true;
            this.btthongke.AllowToggling = false;
            this.btthongke.AnimationSpeed = 200;
            this.btthongke.AutoGenerateColors = false;
            this.btthongke.AutoRoundBorders = false;
            this.btthongke.AutoSizeLeftIcon = true;
            this.btthongke.AutoSizeRightIcon = true;
            this.btthongke.BackColor = System.Drawing.Color.Transparent;
            this.btthongke.BackColor1 = System.Drawing.Color.Transparent;
            this.btthongke.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btthongke.BackgroundImage")));
            this.btthongke.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btthongke.ButtonText = "       Thống Kê";
            this.btthongke.ButtonTextMarginLeft = 0;
            this.btthongke.ColorContrastOnClick = 0;
            this.btthongke.ColorContrastOnHover = 0;
            this.btthongke.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btthongke.CustomizableEdges = borderEdges2;
            this.btthongke.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btthongke.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btthongke.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btthongke.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btthongke.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btthongke.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btthongke.ForeColor = System.Drawing.Color.Gray;
            this.btthongke.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btthongke.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btthongke.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btthongke.IconMarginLeft = 11;
            this.btthongke.IconPadding = 10;
            this.btthongke.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btthongke.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btthongke.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btthongke.IconSize = 25;
            this.btthongke.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btthongke.IdleBorderRadius = 30;
            this.btthongke.IdleBorderThickness = 1;
            this.btthongke.IdleFillColor = System.Drawing.Color.Transparent;
            this.btthongke.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.bar_chart_935491;
            this.btthongke.IdleIconRightImage = null;
            this.btthongke.IndicateFocus = false;
            this.btthongke.Location = new System.Drawing.Point(10, 496);
            this.btthongke.Name = "btthongke";
            this.btthongke.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btthongke.OnDisabledState.BorderRadius = 30;
            this.btthongke.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btthongke.OnDisabledState.BorderThickness = 1;
            this.btthongke.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btthongke.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btthongke.OnDisabledState.IconLeftImage = null;
            this.btthongke.OnDisabledState.IconRightImage = null;
            this.btthongke.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btthongke.onHoverState.BorderRadius = 30;
            this.btthongke.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btthongke.onHoverState.BorderThickness = 1;
            this.btthongke.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btthongke.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btthongke.onHoverState.IconLeftImage = null;
            this.btthongke.onHoverState.IconRightImage = null;
            this.btthongke.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btthongke.OnIdleState.BorderRadius = 30;
            this.btthongke.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btthongke.OnIdleState.BorderThickness = 1;
            this.btthongke.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btthongke.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btthongke.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.bar_chart_935491;
            this.btthongke.OnIdleState.IconRightImage = null;
            this.btthongke.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btthongke.OnPressedState.BorderRadius = 30;
            this.btthongke.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btthongke.OnPressedState.BorderThickness = 1;
            this.btthongke.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btthongke.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btthongke.OnPressedState.IconLeftImage = null;
            this.btthongke.OnPressedState.IconRightImage = null;
            this.btthongke.Size = new System.Drawing.Size(251, 62);
            this.btthongke.TabIndex = 7;
            this.btthongke.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btthongke.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btthongke.TextMarginLeft = 0;
            this.btthongke.TextPadding = new System.Windows.Forms.Padding(0);
            this.btthongke.UseDefaultRadiusAndThickness = true;
            this.btthongke.Click += new System.EventHandler(this.btthongke_Click);
            // 
            // btquanlinhanvien
            // 
            this.btquanlinhanvien.AllowAnimations = true;
            this.btquanlinhanvien.AllowMouseEffects = true;
            this.btquanlinhanvien.AllowToggling = false;
            this.btquanlinhanvien.AnimationSpeed = 200;
            this.btquanlinhanvien.AutoGenerateColors = false;
            this.btquanlinhanvien.AutoRoundBorders = false;
            this.btquanlinhanvien.AutoSizeLeftIcon = true;
            this.btquanlinhanvien.AutoSizeRightIcon = true;
            this.btquanlinhanvien.BackColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.BackColor1 = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btquanlinhanvien.BackgroundImage")));
            this.btquanlinhanvien.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btquanlinhanvien.ButtonText = "        Nhân Viên";
            this.btquanlinhanvien.ButtonTextMarginLeft = 0;
            this.btquanlinhanvien.ColorContrastOnClick = 0;
            this.btquanlinhanvien.ColorContrastOnHover = 0;
            this.btquanlinhanvien.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btquanlinhanvien.CustomizableEdges = borderEdges3;
            this.btquanlinhanvien.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btquanlinhanvien.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btquanlinhanvien.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btquanlinhanvien.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btquanlinhanvien.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btquanlinhanvien.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btquanlinhanvien.ForeColor = System.Drawing.Color.Gray;
            this.btquanlinhanvien.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btquanlinhanvien.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btquanlinhanvien.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btquanlinhanvien.IconMarginLeft = 11;
            this.btquanlinhanvien.IconPadding = 10;
            this.btquanlinhanvien.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btquanlinhanvien.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btquanlinhanvien.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btquanlinhanvien.IconSize = 25;
            this.btquanlinhanvien.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.IdleBorderRadius = 30;
            this.btquanlinhanvien.IdleBorderThickness = 1;
            this.btquanlinhanvien.IdleFillColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.manager_12061875;
            this.btquanlinhanvien.IdleIconRightImage = null;
            this.btquanlinhanvien.IndicateFocus = false;
            this.btquanlinhanvien.Location = new System.Drawing.Point(10, 590);
            this.btquanlinhanvien.Name = "btquanlinhanvien";
            this.btquanlinhanvien.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btquanlinhanvien.OnDisabledState.BorderRadius = 30;
            this.btquanlinhanvien.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btquanlinhanvien.OnDisabledState.BorderThickness = 1;
            this.btquanlinhanvien.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btquanlinhanvien.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btquanlinhanvien.OnDisabledState.IconLeftImage = null;
            this.btquanlinhanvien.OnDisabledState.IconRightImage = null;
            this.btquanlinhanvien.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btquanlinhanvien.onHoverState.BorderRadius = 30;
            this.btquanlinhanvien.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btquanlinhanvien.onHoverState.BorderThickness = 1;
            this.btquanlinhanvien.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btquanlinhanvien.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btquanlinhanvien.onHoverState.IconLeftImage = null;
            this.btquanlinhanvien.onHoverState.IconRightImage = null;
            this.btquanlinhanvien.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.OnIdleState.BorderRadius = 30;
            this.btquanlinhanvien.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btquanlinhanvien.OnIdleState.BorderThickness = 1;
            this.btquanlinhanvien.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btquanlinhanvien.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.manager_12061875;
            this.btquanlinhanvien.OnIdleState.IconRightImage = null;
            this.btquanlinhanvien.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btquanlinhanvien.OnPressedState.BorderRadius = 30;
            this.btquanlinhanvien.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btquanlinhanvien.OnPressedState.BorderThickness = 1;
            this.btquanlinhanvien.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btquanlinhanvien.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btquanlinhanvien.OnPressedState.IconLeftImage = null;
            this.btquanlinhanvien.OnPressedState.IconRightImage = null;
            this.btquanlinhanvien.Size = new System.Drawing.Size(251, 62);
            this.btquanlinhanvien.TabIndex = 6;
            this.btquanlinhanvien.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btquanlinhanvien.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btquanlinhanvien.TextMarginLeft = 0;
            this.btquanlinhanvien.TextPadding = new System.Windows.Forms.Padding(0);
            this.btquanlinhanvien.UseDefaultRadiusAndThickness = true;
            this.btquanlinhanvien.Click += new System.EventHandler(this.btquanlinhanvien_Click);
            // 
            // btnhapdon
            // 
            this.btnhapdon.AllowAnimations = true;
            this.btnhapdon.AllowMouseEffects = true;
            this.btnhapdon.AllowToggling = false;
            this.btnhapdon.AnimationSpeed = 200;
            this.btnhapdon.AutoGenerateColors = false;
            this.btnhapdon.AutoRoundBorders = false;
            this.btnhapdon.AutoSizeLeftIcon = true;
            this.btnhapdon.AutoSizeRightIcon = true;
            this.btnhapdon.BackColor = System.Drawing.Color.Transparent;
            this.btnhapdon.BackColor1 = System.Drawing.Color.Transparent;
            this.btnhapdon.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnhapdon.BackgroundImage")));
            this.btnhapdon.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhapdon.ButtonText = "       Nhập Đơn";
            this.btnhapdon.ButtonTextMarginLeft = 0;
            this.btnhapdon.ColorContrastOnClick = 0;
            this.btnhapdon.ColorContrastOnHover = 0;
            this.btnhapdon.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnhapdon.CustomizableEdges = borderEdges4;
            this.btnhapdon.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnhapdon.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhapdon.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhapdon.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhapdon.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnhapdon.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnhapdon.ForeColor = System.Drawing.Color.Gray;
            this.btnhapdon.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnhapdon.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnhapdon.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnhapdon.IconMarginLeft = 11;
            this.btnhapdon.IconPadding = 10;
            this.btnhapdon.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnhapdon.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnhapdon.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnhapdon.IconSize = 25;
            this.btnhapdon.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnhapdon.IdleBorderRadius = 30;
            this.btnhapdon.IdleBorderThickness = 1;
            this.btnhapdon.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnhapdon.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.package_1333031;
            this.btnhapdon.IdleIconRightImage = null;
            this.btnhapdon.IndicateFocus = false;
            this.btnhapdon.Location = new System.Drawing.Point(10, 402);
            this.btnhapdon.Name = "btnhapdon";
            this.btnhapdon.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhapdon.OnDisabledState.BorderRadius = 30;
            this.btnhapdon.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhapdon.OnDisabledState.BorderThickness = 1;
            this.btnhapdon.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhapdon.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhapdon.OnDisabledState.IconLeftImage = null;
            this.btnhapdon.OnDisabledState.IconRightImage = null;
            this.btnhapdon.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btnhapdon.onHoverState.BorderRadius = 30;
            this.btnhapdon.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhapdon.onHoverState.BorderThickness = 1;
            this.btnhapdon.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btnhapdon.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btnhapdon.onHoverState.IconLeftImage = null;
            this.btnhapdon.onHoverState.IconRightImage = null;
            this.btnhapdon.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnhapdon.OnIdleState.BorderRadius = 30;
            this.btnhapdon.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhapdon.OnIdleState.BorderThickness = 1;
            this.btnhapdon.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnhapdon.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btnhapdon.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.package_1333031;
            this.btnhapdon.OnIdleState.IconRightImage = null;
            this.btnhapdon.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnhapdon.OnPressedState.BorderRadius = 30;
            this.btnhapdon.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhapdon.OnPressedState.BorderThickness = 1;
            this.btnhapdon.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btnhapdon.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btnhapdon.OnPressedState.IconLeftImage = null;
            this.btnhapdon.OnPressedState.IconRightImage = null;
            this.btnhapdon.Size = new System.Drawing.Size(251, 62);
            this.btnhapdon.TabIndex = 5;
            this.btnhapdon.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnhapdon.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnhapdon.TextMarginLeft = 0;
            this.btnhapdon.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnhapdon.UseDefaultRadiusAndThickness = true;
            this.btnhapdon.Click += new System.EventHandler(this.btnhapdon_Click);
            // 
            // btkhohang
            // 
            this.btkhohang.AllowAnimations = true;
            this.btkhohang.AllowMouseEffects = true;
            this.btkhohang.AllowToggling = false;
            this.btkhohang.AnimationSpeed = 200;
            this.btkhohang.AutoGenerateColors = false;
            this.btkhohang.AutoRoundBorders = false;
            this.btkhohang.AutoSizeLeftIcon = true;
            this.btkhohang.AutoSizeRightIcon = true;
            this.btkhohang.BackColor = System.Drawing.Color.Transparent;
            this.btkhohang.BackColor1 = System.Drawing.Color.Transparent;
            this.btkhohang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btkhohang.BackgroundImage")));
            this.btkhohang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btkhohang.ButtonText = "       Kho Hàng";
            this.btkhohang.ButtonTextMarginLeft = 0;
            this.btkhohang.ColorContrastOnClick = 0;
            this.btkhohang.ColorContrastOnHover = 0;
            this.btkhohang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btkhohang.CustomizableEdges = borderEdges5;
            this.btkhohang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btkhohang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btkhohang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btkhohang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btkhohang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btkhohang.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btkhohang.ForeColor = System.Drawing.Color.Gray;
            this.btkhohang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btkhohang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btkhohang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btkhohang.IconMarginLeft = 11;
            this.btkhohang.IconPadding = 10;
            this.btkhohang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btkhohang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btkhohang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btkhohang.IconSize = 25;
            this.btkhohang.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btkhohang.IdleBorderRadius = 30;
            this.btkhohang.IdleBorderThickness = 1;
            this.btkhohang.IdleFillColor = System.Drawing.Color.Transparent;
            this.btkhohang.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.laptop_1876543;
            this.btkhohang.IdleIconRightImage = null;
            this.btkhohang.IndicateFocus = false;
            this.btkhohang.Location = new System.Drawing.Point(10, 308);
            this.btkhohang.Name = "btkhohang";
            this.btkhohang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btkhohang.OnDisabledState.BorderRadius = 30;
            this.btkhohang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btkhohang.OnDisabledState.BorderThickness = 1;
            this.btkhohang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btkhohang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btkhohang.OnDisabledState.IconLeftImage = null;
            this.btkhohang.OnDisabledState.IconRightImage = null;
            this.btkhohang.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btkhohang.onHoverState.BorderRadius = 30;
            this.btkhohang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btkhohang.onHoverState.BorderThickness = 1;
            this.btkhohang.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btkhohang.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btkhohang.onHoverState.IconLeftImage = null;
            this.btkhohang.onHoverState.IconRightImage = null;
            this.btkhohang.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btkhohang.OnIdleState.BorderRadius = 30;
            this.btkhohang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btkhohang.OnIdleState.BorderThickness = 1;
            this.btkhohang.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btkhohang.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btkhohang.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.laptop_1876543;
            this.btkhohang.OnIdleState.IconRightImage = null;
            this.btkhohang.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btkhohang.OnPressedState.BorderRadius = 30;
            this.btkhohang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btkhohang.OnPressedState.BorderThickness = 1;
            this.btkhohang.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btkhohang.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btkhohang.OnPressedState.IconLeftImage = null;
            this.btkhohang.OnPressedState.IconRightImage = null;
            this.btkhohang.Size = new System.Drawing.Size(251, 62);
            this.btkhohang.TabIndex = 4;
            this.btkhohang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btkhohang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btkhohang.TextMarginLeft = 0;
            this.btkhohang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btkhohang.UseDefaultRadiusAndThickness = true;
            this.btkhohang.Click += new System.EventHandler(this.btkhohang_Click);
            // 
            // btqldonhang
            // 
            this.btqldonhang.AllowAnimations = true;
            this.btqldonhang.AllowMouseEffects = true;
            this.btqldonhang.AllowToggling = false;
            this.btqldonhang.AnimationSpeed = 200;
            this.btqldonhang.AutoGenerateColors = false;
            this.btqldonhang.AutoRoundBorders = false;
            this.btqldonhang.AutoSizeLeftIcon = true;
            this.btqldonhang.AutoSizeRightIcon = true;
            this.btqldonhang.BackColor = System.Drawing.Color.Transparent;
            this.btqldonhang.BackColor1 = System.Drawing.Color.Transparent;
            this.btqldonhang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btqldonhang.BackgroundImage")));
            this.btqldonhang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btqldonhang.ButtonText = "        Đơn Hàng";
            this.btqldonhang.ButtonTextMarginLeft = 0;
            this.btqldonhang.ColorContrastOnClick = 0;
            this.btqldonhang.ColorContrastOnHover = 0;
            this.btqldonhang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btqldonhang.CustomizableEdges = borderEdges6;
            this.btqldonhang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btqldonhang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btqldonhang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btqldonhang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btqldonhang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btqldonhang.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btqldonhang.ForeColor = System.Drawing.Color.Gray;
            this.btqldonhang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btqldonhang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btqldonhang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btqldonhang.IconMarginLeft = 11;
            this.btqldonhang.IconPadding = 10;
            this.btqldonhang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btqldonhang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btqldonhang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btqldonhang.IconSize = 25;
            this.btqldonhang.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btqldonhang.IdleBorderRadius = 30;
            this.btqldonhang.IdleBorderThickness = 1;
            this.btqldonhang.IdleFillColor = System.Drawing.Color.Transparent;
            this.btqldonhang.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.shopping_list_15107485;
            this.btqldonhang.IdleIconRightImage = null;
            this.btqldonhang.IndicateFocus = false;
            this.btqldonhang.Location = new System.Drawing.Point(10, 214);
            this.btqldonhang.Name = "btqldonhang";
            this.btqldonhang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btqldonhang.OnDisabledState.BorderRadius = 30;
            this.btqldonhang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btqldonhang.OnDisabledState.BorderThickness = 1;
            this.btqldonhang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btqldonhang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btqldonhang.OnDisabledState.IconLeftImage = null;
            this.btqldonhang.OnDisabledState.IconRightImage = null;
            this.btqldonhang.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btqldonhang.onHoverState.BorderRadius = 30;
            this.btqldonhang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btqldonhang.onHoverState.BorderThickness = 1;
            this.btqldonhang.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btqldonhang.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btqldonhang.onHoverState.IconLeftImage = null;
            this.btqldonhang.onHoverState.IconRightImage = null;
            this.btqldonhang.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btqldonhang.OnIdleState.BorderRadius = 30;
            this.btqldonhang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btqldonhang.OnIdleState.BorderThickness = 1;
            this.btqldonhang.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btqldonhang.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btqldonhang.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.shopping_list_15107485;
            this.btqldonhang.OnIdleState.IconRightImage = null;
            this.btqldonhang.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btqldonhang.OnPressedState.BorderRadius = 30;
            this.btqldonhang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btqldonhang.OnPressedState.BorderThickness = 1;
            this.btqldonhang.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btqldonhang.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btqldonhang.OnPressedState.IconLeftImage = null;
            this.btqldonhang.OnPressedState.IconRightImage = null;
            this.btqldonhang.Size = new System.Drawing.Size(251, 62);
            this.btqldonhang.TabIndex = 3;
            this.btqldonhang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btqldonhang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btqldonhang.TextMarginLeft = 0;
            this.btqldonhang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btqldonhang.UseDefaultRadiusAndThickness = true;
            this.btqldonhang.Click += new System.EventHandler(this.btqldonhang_Click);
            // 
            // btbanhang
            // 
            this.btbanhang.AllowAnimations = true;
            this.btbanhang.AllowMouseEffects = true;
            this.btbanhang.AllowToggling = false;
            this.btbanhang.AnimationSpeed = 200;
            this.btbanhang.AutoGenerateColors = false;
            this.btbanhang.AutoRoundBorders = false;
            this.btbanhang.AutoSizeLeftIcon = true;
            this.btbanhang.AutoSizeRightIcon = true;
            this.btbanhang.BackColor = System.Drawing.Color.Transparent;
            this.btbanhang.BackColor1 = System.Drawing.Color.Transparent;
            this.btbanhang.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btbanhang.BackgroundImage")));
            this.btbanhang.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btbanhang.ButtonText = "      Bán Hàng";
            this.btbanhang.ButtonTextMarginLeft = 0;
            this.btbanhang.ColorContrastOnClick = 0;
            this.btbanhang.ColorContrastOnHover = 0;
            this.btbanhang.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btbanhang.CustomizableEdges = borderEdges7;
            this.btbanhang.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btbanhang.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btbanhang.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btbanhang.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btbanhang.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btbanhang.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btbanhang.ForeColor = System.Drawing.Color.Gray;
            this.btbanhang.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btbanhang.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btbanhang.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btbanhang.IconMarginLeft = 11;
            this.btbanhang.IconPadding = 10;
            this.btbanhang.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btbanhang.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btbanhang.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btbanhang.IconSize = 25;
            this.btbanhang.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btbanhang.IdleBorderRadius = 30;
            this.btbanhang.IdleBorderThickness = 1;
            this.btbanhang.IdleFillColor = System.Drawing.Color.Transparent;
            this.btbanhang.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.product_9660170;
            this.btbanhang.IdleIconRightImage = null;
            this.btbanhang.IndicateFocus = false;
            this.btbanhang.Location = new System.Drawing.Point(10, 120);
            this.btbanhang.Name = "btbanhang";
            this.btbanhang.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btbanhang.OnDisabledState.BorderRadius = 30;
            this.btbanhang.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btbanhang.OnDisabledState.BorderThickness = 1;
            this.btbanhang.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btbanhang.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btbanhang.OnDisabledState.IconLeftImage = null;
            this.btbanhang.OnDisabledState.IconRightImage = null;
            this.btbanhang.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.btbanhang.onHoverState.BorderRadius = 30;
            this.btbanhang.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btbanhang.onHoverState.BorderThickness = 1;
            this.btbanhang.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btbanhang.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.btbanhang.onHoverState.IconLeftImage = null;
            this.btbanhang.onHoverState.IconRightImage = null;
            this.btbanhang.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btbanhang.OnIdleState.BorderRadius = 30;
            this.btbanhang.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btbanhang.OnIdleState.BorderThickness = 1;
            this.btbanhang.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btbanhang.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.btbanhang.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.product_9660170;
            this.btbanhang.OnIdleState.IconRightImage = null;
            this.btbanhang.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btbanhang.OnPressedState.BorderRadius = 30;
            this.btbanhang.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btbanhang.OnPressedState.BorderThickness = 1;
            this.btbanhang.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.btbanhang.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.btbanhang.OnPressedState.IconLeftImage = null;
            this.btbanhang.OnPressedState.IconRightImage = null;
            this.btbanhang.Size = new System.Drawing.Size(251, 62);
            this.btbanhang.TabIndex = 2;
            this.btbanhang.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btbanhang.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btbanhang.TextMarginLeft = 0;
            this.btbanhang.TextPadding = new System.Windows.Forms.Padding(0);
            this.btbanhang.UseDefaultRadiusAndThickness = true;
            this.btbanhang.Click += new System.EventHandler(this.btbanhang_Click);
            // 
            // bthome
            // 
            this.bthome.AllowAnimations = true;
            this.bthome.AllowMouseEffects = true;
            this.bthome.AllowToggling = false;
            this.bthome.AnimationSpeed = 200;
            this.bthome.AutoGenerateColors = false;
            this.bthome.AutoRoundBorders = false;
            this.bthome.AutoSizeLeftIcon = true;
            this.bthome.AutoSizeRightIcon = true;
            this.bthome.BackColor = System.Drawing.Color.Transparent;
            this.bthome.BackColor1 = System.Drawing.Color.Transparent;
            this.bthome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bthome.BackgroundImage")));
            this.bthome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bthome.ButtonText = "       Trang Chủ";
            this.bthome.ButtonTextMarginLeft = 0;
            this.bthome.ColorContrastOnClick = 0;
            this.bthome.ColorContrastOnHover = 0;
            this.bthome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bthome.CustomizableEdges = borderEdges8;
            this.bthome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bthome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bthome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bthome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bthome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bthome.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bthome.ForeColor = System.Drawing.Color.Gray;
            this.bthome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bthome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bthome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bthome.IconMarginLeft = 11;
            this.bthome.IconPadding = 10;
            this.bthome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bthome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bthome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bthome.IconSize = 25;
            this.bthome.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bthome.IdleBorderRadius = 30;
            this.bthome.IdleBorderThickness = 1;
            this.bthome.IdleFillColor = System.Drawing.Color.Transparent;
            this.bthome.IdleIconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.home_4561523;
            this.bthome.IdleIconRightImage = null;
            this.bthome.IndicateFocus = false;
            this.bthome.Location = new System.Drawing.Point(10, 26);
            this.bthome.Name = "bthome";
            this.bthome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bthome.OnDisabledState.BorderRadius = 30;
            this.bthome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bthome.OnDisabledState.BorderThickness = 1;
            this.bthome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bthome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bthome.OnDisabledState.IconLeftImage = null;
            this.bthome.OnDisabledState.IconRightImage = null;
            this.bthome.onHoverState.BorderColor = System.Drawing.Color.Teal;
            this.bthome.onHoverState.BorderRadius = 30;
            this.bthome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bthome.onHoverState.BorderThickness = 1;
            this.bthome.onHoverState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.bthome.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.bthome.onHoverState.IconLeftImage = null;
            this.bthome.onHoverState.IconRightImage = null;
            this.bthome.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.bthome.OnIdleState.BorderRadius = 30;
            this.bthome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bthome.OnIdleState.BorderThickness = 1;
            this.bthome.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.bthome.OnIdleState.ForeColor = System.Drawing.Color.Gray;
            this.bthome.OnIdleState.IconLeftImage = global::ELEVATE_SHOP_MANAGER.Properties.Resources.home_4561523;
            this.bthome.OnIdleState.IconRightImage = null;
            this.bthome.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.bthome.OnPressedState.BorderRadius = 30;
            this.bthome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bthome.OnPressedState.BorderThickness = 1;
            this.bthome.OnPressedState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.bthome.OnPressedState.ForeColor = System.Drawing.Color.DarkSlateGray;
            this.bthome.OnPressedState.IconLeftImage = null;
            this.bthome.OnPressedState.IconRightImage = null;
            this.bthome.Size = new System.Drawing.Size(251, 63);
            this.bthome.TabIndex = 1;
            this.bthome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bthome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bthome.TextMarginLeft = 0;
            this.bthome.TextPadding = new System.Windows.Forms.Padding(0);
            this.bthome.UseDefaultRadiusAndThickness = true;
            this.bthome.Click += new System.EventHandler(this.bthome_Click);
            // 
            // Conten
            // 
            this.Conten.BackColor = System.Drawing.Color.Gray;
            this.Conten.BorderColor = System.Drawing.Color.Gray;
            this.Conten.BorderRadius = 1;
            this.Conten.BorderThickness = 1;
            this.Conten.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Conten.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Conten.LabelIndent = 10;
            this.Conten.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.Conten.Location = new System.Drawing.Point(277, 71);
            this.Conten.Name = "Conten";
            this.Conten.Padding = new System.Windows.Forms.Padding(0);
            this.Conten.Size = new System.Drawing.Size(1635, 924);
            this.Conten.TabIndex = 2;
            this.Conten.TabStop = false;
            // 
            // home
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1924, 1033);
            this.Controls.Add(this.Conten);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Controls.Add(this.bunifuGroupBox1);
            this.ForeColor = System.Drawing.Color.White;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "home";
            this.Text = "ELEVATE MANAGER ";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.home_FormClosing);
            this.Load += new System.EventHandler(this.home_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.bunifuGroupBox2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
        private Bunifu.UI.WinForms.BunifuGroupBox Conten;
        private System.Windows.Forms.Label name;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bthome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btqldonhang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btbanhang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btthongke;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btquanlinhanvien;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnhapdon;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btkhohang;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton27;
        private System.Windows.Forms.Label label2;
    }
}